[tool.black]
line-length = 119
target_version = ['py312']

[tool.ruff]
# Ignored rules:
#   "E501" -> line length violation
#   "F821" -> undefined named in type annotation (e.g. Literal["something"])
lint.ignore = ["E501", "F821"]
lint.select = ["E", "F", "I", "W"]
line-length = 119

[tool.ruff.lint.isort]
lines-after-imports = 2
